### ISSUE TITLE
Should i download 30Gb of Freebase ?

### ISSUE THREAD

**Issue by GraphGrailAi** [PetrochukM/Simple-QA-EMNLP-2018#6]
Him in notebooks/Simple QA KG to PostgreSQL DB/Full Freebase to DB.ipynb
i see:
The dump of Freebase can be found here: https://developers.google.com/freebase

Should i download 30Gb of Freebase ? it is 250 gb unzipped

**Comment by PetrochukM** [comment]
You can download Freebase if you want.
